FROM logstash:7.16.3 AS builder
WORKDIR /usr/share/logstash

FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.3

RUN mkdir -p /usr/share/logstash/x-pack/lib/filters
COPY --from=builder /usr/share/logstash/x-pack/lib/filters/geoip /usr/share/logstash/x-pack/lib/filters/geoip
ENV OSS=true



USER logstash
